log_level: INFO

accounts:
# - id: demo
#   driver: rubykube
#   debug: false
#   host: "https://demo.openware.com"
#   ws: "wss://demo.openware.com"
#   key: "df6330db624fcc67"
#   secret: "c2ac593fd25281a4cbf9df6f88d700a0"
#   delay: 1

- id: bitfaker-source
  driver: bitfaker
  delay: 1

- id: bitfaker-target
  driver: bitfaker
  delay: [0.8, 1, 3]
  key: anything
  secret: 42
  orderbook: [1,[]]
  params:
    balances:
      - currency: btc
        total: 3
        free: 3
        locked: 0
      - currency: usd
        total: 10000
        free: 10000
        locked: 0

strategies:
- id: skew-ETHUSD
  type: skew
  params:
    spread_ask: 0.003
    spread_bid: 0.003
    levels_price_step: 5
    levels_size: 1
    levels_price_func: linear
    levels_count: 6
    target_base_balance_in_quote: 1000
    max_skew_perc: 0.5

  target:
    account_id: bitfaker-target
    market_id: ethusd
  sources:
  - account_id: bitfaker-source
    market_id: ETHUSD

- id: copy-ETHUSD
  type: copy
  enabled: true
  period: 30
  delay: [0.3, 0.7, 1.3]
  params:
    limit_asks_base: 100
    limit_bids_base: 100
    max_amount_per_order: 10
    levels_price_step: 5
    levels_size: 1
    levels_price_func: linear
    levels_count: 6
    side: both
  target:
    account_id: bitfaker-target
    market_id: ethusd

  sources:
  - account_id: bitfaker-source
    market_id: ETHUSD

# - id: copy-ETHUSD
#   type: simple-copy
#   enabled: true
#   period: 30
#   params:
#     spread_bids: 0.003
#     spread_asks: 0.003
#     max_amount_per_order: 1
#     levels_price_step: 5
#     levels_price_func: linear
#     levels_count: 6
#     shape: custom
#     levels: [0.1, 0.2, 1, 2, 0.1]
#   target:
#     account_id: bitfaker-target
#     market_id: ethusd

#   sources:
#   - account_id: bitfaker-source
#     market_id: ETHUSD

# - id: microtrades-FTHUSD
#   type: microtrades
#   debug: true
#   enabled: false
#   period: 5
#   period_random_delay: 10
#   params:
#     linked_strategy_id: copy-FTHUSD
#     min_amount: 0.05
#     max_amount: 0.30
#   target:
#       account_id: demo
#       market_id: ethusd
